name: clima_app2
description: "Aplicativo de clima feito com Flutter."


publish_to: "none" # Créditos visuais: https://icons8.com.br/

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# 📦 Dependências principais
dependencies:
  flutter:
    sdk: flutter

  # 🌐 UI e ícones
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  weather_icons: ^3.0.0
  flutter_spinkit: ^5.2.1

  # 🌍 Localização e clima
  dio: ^5.8.0+1
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # ⚙️ Estado e armazenamento
  get: ^4.7.2
  get_storage: ^2.1.1

  # 🔐 Variáveis de ambiente
  flutter_dotenv: ^6.0.0 

  # 🚀 Splash screen personalizada
  flutter_native_splash: ^2.4.6

# ⚙️ Configuração do splash screen
flutter_native_splash:
  color: "#121212"
  color_dark: "#121212"
  image: assets/splash_logo/logo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

# 🧪 Dependências de desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  geolocator_platform_interface: ^4.0.0

# 🎯 Configurações do Flutter
flutter:
  uses-material-design: true

  # 🅰️ Fontes personalizadas
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf

  # 🖼️ Diretórios de assets
  assets:
    - assets/splash_logo/
    - assets/fonts/