name: Flutter CI

on:
  push:
    branches: [ Emanoel ]
  pull_request:
    branches: [ Emanoel]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get
      - name: Run integration tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: default
          profile: Nexus 6
          script: |
            flutter drive \
              --driver=test_driver/integration_test.dart \
              --target=integration_test/localization_test.dart
            flutter drive \
              --driver=test_driver/integration_test.dart \
              --target=integration_test/get_storage_test.dart

  build-apk:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
